config/routes.rb
Rails.application.routes.draw do
  resources :memory_tests
  resources :memory_checks
  resources :tests
  root 'home#index'

  devise_for :users

end

app/models/memory_test.rb
class MemoryTest < ActiveRecord::Base
  belongs_to :user
# Before we save to the database we run the check_answers function
  before_save :check_answers
  
# This is a function or method
  def check_answers
    # Create a variable to record the score
    test_score = 0
    
    # Test is each user's answer matches the real answer
    # If they match, we increment the score
    if self.qName == "Jamie"
       test_score = test_score + 1
    end
    
    if self.qBirthday == "19 May"
       test_score = test_score + 1
    end
    
    if self.qSuburb == "Bondi"
       test_score = test_score + 1
    end
    
    if self.qPet == "Jack"
       test_score = test_score + 1
    end
    
    if self.qSchool == "Coder Factory"
       test_score = test_score + 1
    end
    
    if self.qJob == "CEO"
       test_score = test_score + 1
    end
    
    if self.qGrandchildren == "3"
       test_score = test_score + 1
    end
    
    self.score = test_score
  end
end

app/controllers/memory_tests_controller.rb
class MemoryTestsController < ApplicationController
  before_action :set_memory_test, only: [:show, :edit, :update, :destroy]

  # GET /memory_tests
  # GET /memory_tests.json
  def index
    @memory_tests = MemoryTest.all
  end

  # GET /memory_tests/1
  # GET /memory_tests/1.json
  def show
  end

  # GET /memory_tests/new
  def new
    @memory_test = MemoryTest.new
  end

  # GET /memory_tests/1/edit
  def edit
  end

  # POST /memory_tests
  # POST /memory_tests.json
  def create
    @memory_test = MemoryTest.new(memory_test_params)
    @memory_test.user = current_user

    respond_to do |format|
      if @memory_test.save
        format.html { redirect_to @memory_test, notice: 'Memory test was successfully created.' }
        format.json { render :show, status: :created, location: @memory_test }
      else
        format.html { render :new }
        format.json { render json: @memory_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memory_tests/1
  # PATCH/PUT /memory_tests/1.json
  def update
    respond_to do |format|
      if @memory_test.update(memory_test_params)
        format.html { redirect_to @memory_test, notice: 'Memory test was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory_test }
      else
        format.html { render :edit }
        format.json { render json: @memory_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memory_tests/1
  # DELETE /memory_tests/1.json
  def destroy
    @memory_test.destroy
    respond_to do |format|
      format.html { redirect_to memory_tests_url, notice: 'Memory test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory_test
      @memory_test = MemoryTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_test_params
      params.require(:memory_test).permit(:qName, :qBirthday, :qSuburb, :qPet, :qSchool, :qJob, :qGrandchildren, :user_id, :score)
    end
end

app/helpers/memory_tests_helper.rb
module MemoryTestsHelper
end

app/views/memory_tests/_form.html.erb
<%= simple_form_for(@memory_test) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :qName, label: "What is your name?" %>
    <%= f.input :qBirthday, label: "What is your birthday?" %>
    <%= f.input :qSuburb, label: "In which suburb was your first home?" %>
    <%= f.input :qPet, label: "What was the name of your first pet?" %>
    <%= f.input :qSchool, label: "Where did your children go to school?" %>
    <%= f.input :qJob, label: "What was the last job of your career?" %>
    <%= f.input :qGrandchildren, label: "How many grandchildren do you have?" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/memory_tests/edit.html.erb
<h1>Editing Memory Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory_test %> |
<%= link_to 'Back', memory_tests_path %>

app/views/memory_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memory Tests</h1>

<table>
  <thead>
    <tr>
      <th>Date Completed</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memory_tests.each do |memory_test| %>
      <tr>
        <td><%= memory_test.created_at %></td>
        <td><%= memory_test.score %></td>
        <td><%= link_to 'Show', memory_test %></td>
        <td><%= link_to 'Edit', edit_memory_test_path(memory_test) %></td>
        <td><%= link_to 'Destroy', memory_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory test', new_memory_test_path %>

app/views/memory_tests/new.html.erb
<h1>New Memory Test</h1>

<%= render 'form' %>

<%= link_to 'Back', memory_tests_path %>

app/views/memory_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qname:</strong>
  <%= @memory_test.qName %>
</p>

<p>
  <strong>Qbirthday:</strong>
  <%= @memory_test.qBirthday %>
</p>

<p>
  <strong>Qsuburb:</strong>
  <%= @memory_test.qSuburb %>
</p>

<p>
  <strong>Qpet:</strong>
  <%= @memory_test.qPet %>
</p>

<p>
  <strong>Qschool:</strong>
  <%= @memory_test.qSchool %>
</p>

<p>
  <strong>Qjob:</strong>
  <%= @memory_test.qJob %>
</p>

<p>
  <strong>Qgrandchildren:</strong>
  <%= @memory_test.qGrandchildren %>
</p>

<p>
  <strong>User:</strong>
  <%= @memory_test.user %>
</p>

<p>
  <strong>Score:</strong>
  <%= @memory_test.score %>
</p>

<%= link_to 'Edit', edit_memory_test_path(@memory_test) %> |
<%= link_to 'Back', memory_tests_path %>