config/routes.rb
Rails.application.routes.draw do
  resources :memory_tests
  resources :memory_checks
  resources :tests
  root 'home#index'

  devise_for :users

end

app/models/memory_check.rb
class MemoryCheck < ActiveRecord::Base
  belongs_to :user
  before_save :check_answers
  
  def check_answers
    test_score = 0
    if self.q1.downcase == "apple"
        test_score = test_score + 1
    end
    if self.q2.downcase == "banana"
        test_score = test_score + 1
    end
    if self.q3.downcase == "carrot"
        test_score = test_score + 1
    end
    if self.q4.downcase == "delicious"
        test_score = test_score + 1
    end
    if self.q5.downcase == "eggplant"
        test_score = test_score + 1
    end
    if self.q6.downcase == "fruit"
        test_score = test_score + 1
    end
    self.score = test_score
  end
end

app/controllers/memory_checks_controller.rb
class MemoryChecksController < ApplicationController
  before_action :set_memory_check, only: [:show, :edit, :update, :destroy]

  # GET /memory_checks
  # GET /memory_checks.json
  def index
    @memory_checks = MemoryCheck.all
  end

  # GET /memory_checks/1
  # GET /memory_checks/1.json
  def show
  end

  # GET /memory_checks/new
  def new
    @memory_check = MemoryCheck.new
  end

  # GET /memory_checks/1/edit
  def edit
  end

  # POST /memory_checks
  # POST /memory_checks.json
  def create
    @memory_check = MemoryCheck.new(memory_check_params)
    @memory_check.user_id = current_user.id

    respond_to do |format|
      if @memory_check.save
        format.html { redirect_to @memory_check, notice: 'Memory check was successfully created.' }
        format.json { render :show, status: :created, location: @memory_check }
      else
        format.html { render :new }
        format.json { render json: @memory_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memory_checks/1
  # PATCH/PUT /memory_checks/1.json
  def update
    respond_to do |format|
      if @memory_check.update(memory_check_params)
        format.html { redirect_to @memory_check, notice: 'Memory check was successfully updated.' }
        format.json { render :show, status: :ok, location: @memory_check }
      else
        format.html { render :edit }
        format.json { render json: @memory_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memory_checks/1
  # DELETE /memory_checks/1.json
  def destroy
    @memory_check.destroy
    respond_to do |format|
      format.html { redirect_to memory_checks_url, notice: 'Memory check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory_check
      @memory_check = MemoryCheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memory_check_params
      params.require(:memory_check).permit(:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :user_id, :score)
    end
end

app/helpers/memory_checks_helper.rb
module MemoryChecksHelper
end

app/views/memory_checks/_form.html.erb
<%= simple_form_for(@memory_check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :q1, label: "What fruit starts with an 'a'?" %>
    <%= f.input :q2 %>
    <%= f.input :q3 %>
    <%= f.input :q4 %>
    <%= f.input :q5 %>
    <%= f.input :q6 %>
    <%= f.input :q7 %>
    <%= f.input :q8 %>
    <%= f.input :q9 %>
    <%= f.input :q10 %>
    <%= f.association :user %>
    <%= f.input :score %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memory_checks/edit.html.erb
<h1>Editing Memory Check</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory_check %> |
<%= link_to 'Back', memory_checks_path %>

app/views/memory_checks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memory Checks</h1>

<table>
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th>Q8</th>
      <th>Q9</th>
      <th>Q10</th>
      <th>User</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memory_checks.each do |memory_check| %>
      <tr>
        <td><%= memory_check.q1 %></td>
        <td><%= memory_check.q2 %></td>
        <td><%= memory_check.q3 %></td>
        <td><%= memory_check.q4 %></td>
        <td><%= memory_check.q5 %></td>
        <td><%= memory_check.q6 %></td>
        <td><%= memory_check.q7 %></td>
        <td><%= memory_check.q8 %></td>
        <td><%= memory_check.q9 %></td>
        <td><%= memory_check.q10 %></td>
        <td><%= memory_check.user %></td>
        <td><%= memory_check.score %></td>
        <td><%= link_to 'Show', memory_check %></td>
        <td><%= link_to 'Edit', edit_memory_check_path(memory_check) %></td>
        <td><%= link_to 'Destroy', memory_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory check', new_memory_check_path %>

app/views/memory_checks/new.html.erb
<h1>New Memory Check</h1>

<%= render 'form' %>

<%= link_to 'Back', memory_checks_path %>

app/views/memory_checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @memory_check.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @memory_check.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @memory_check.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @memory_check.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @memory_check.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @memory_check.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @memory_check.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @memory_check.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @memory_check.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @memory_check.q10 %>
</p>

<p>
  <strong>User:</strong>
  <%= @memory_check.user %>
</p>

<p>
  <strong>Score:</strong>
  <%= @memory_check.score %>
</p>

<%= link_to 'Edit', edit_memory_check_path(@memory_check) %> |
<%= link_to 'Back', memory_checks_path %>